index.html
Contains only the structure of main sections, abstract, initial terminology, introduction, basic use cases and bare WebIDL definitions.
=> Initial version.

typescript-defs/.gitignore, typescript-defs/package.json, typescript-defs/wot.d.ts
basically transpiling the webIDL into typescript
=> added draft typescript definitions

index.html
currently WebIDL restructuring for Section 6 only
=> HTML fixes and first try to restructure WebIDL

index.html
Still misses prose/description of WebIDL interfaces, attributes and operation
=> create WebIDL skeleton by fixing all WebIDL issues

index.html
=> Fixes for FPWD 

index.html
=> Small fixes.

index.html
=> Editorial fixes for FPWD

index.html
=> Fix #57, edits

index.html
=> Fix Pubrules issues

index.html
=> Update use cases.

index.html
Also mention where methods throw.
=> Add support for chaining in ExposedThing

index.html
Default false is more sensible for writeable and even more for observable
=> Change ThingProperty defaults

index.html
Fix #127: align names from get/set/run to read/write/invoke
=> WiP: Korea F2F changes

index.html
see https://github.com/w3c/wot-scripting-api/issues/133
=> fix: issue-30, DataSchema type must not be required

index.html
* removes type "Number"
* adds IntegerSchema
* uses dedicated types for minimum/maximum
Please let me know whether these changes match the expectation.
=> add IntegerSchema dictionary

index.html
=> Add algorithm descriptions

index.html
As discussed on the Scripting call of 3. Sep.,
- Remove ThingInstance, IOW merge it to ConsumedThing and ExposedThing
- Add algorithms for ExposedThing.expose() and destroy().
=> Simplifications

index.html
=> Fix #144: add setActionHandler()

index.html
=> Fix PropertyWriteHandler text

index.html
This is the initial text for the Security & Privacy section for your comments with normative SHOULD statements.
=> Updating the content of security & privacy section

typescript/README.md, typescript/index.d.ts, typescript/package.json, typescript/tsconfig.json
move https://github.com/thingweb/wot-typescript-definitions to scripting api repository
=> move https://github.com/thingweb/wot-typescript-definitions to scripting repo

typescript/README.md, typescript/index.d.ts, typescript/package.json
Updated wot-typescript-definitions to follow TD Editors' Draft
=> Typescript update

index.html
=> Add appendix for WebIDL index

index.html
Commented out a few outdated use cases. Added notes to the disputed ones.
Revised terminology.
=> Revise scripting use cases and terminology.

index.html
Fix #169: Property observation
=> WiP: Editorial sweep

CODE_OF_CONDUCT.md, Overview.html, README.md, diff.html, index.html, releases/wd2/Overview.html, releases/wd2/diff.html, releases/wd3/Overview.html, releases/wd3/diff.html, releases/wd3/manifest.txt, typescript/README.md, typescript/index.d.ts, typescript/package.json, typescript/tsconfig.json, w3c.json
Needed for drafting a simplified split API.
=> Rebase the draft branch

index.html
Fixing #173 
Other small fixes.
=> Separate client and server API

index.html
=> Correct Web IDL for new errors. Add ed note for iterables.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/189.html" title="Last updated on Sep 9, 2019, 12:17 PM UTC (2992fbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/189/9244afb...zolkis:2992fbf.html" title="Last updated on Sep 9, 2019, 12:17 PM UTC (2992fbf)">Diff</a>
=> Update constructors. Add InteractionOptions to handlers.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/195.html" title="Last updated on Sep 27, 2019, 1:05 PM UTC (2b6e728)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/195/e7c34db...zolkis:2b6e728.html" title="Last updated on Sep 27, 2019, 1:05 PM UTC (2b6e728)">Diff</a>
=> Fix HTML errors

index.html
Small, agreed changes to the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/203.html" title="Last updated on Feb 20, 2020, 11:21 AM UTC (2c8801a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/203/285cb81...zolkis:2c8801a.html" title="Last updated on Feb 20, 2020, 11:21 AM UTC (2c8801a)">Diff</a>
=> Fix markdown, add formIndex, explain write handlers

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/236.html" title="Last updated on Aug 17, 2020, 3:04 PM UTC (270cb0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/236/b4537b9...270cb0c.html" title="Last updated on Aug 17, 2020, 3:04 PM UTC (270cb0c)">Diff</a>
=> minor: remove duplicated as

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/246.html" title="Last updated on Aug 24, 2020, 2:05 PM UTC (b50b6f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/246/75dc2b2...zolkis:b50b6f8.html" title="Last updated on Aug 24, 2020, 2:05 PM UTC (b50b6f8)">Diff</a>
=> Add Cristiano Aguzzi as Editor

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/249.html" title="Last updated on Aug 25, 2020, 1:54 PM UTC (a6893f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/249/db86ec8...a6893f1.html" title="Last updated on Aug 25, 2020, 1:54 PM UTC (a6893f1)">Diff</a>
=> example: fix/add missing bracket

index.html
This PR contains the changes that I'd make to the final published document. They are open to discussion. The PR is still a work in progress since I reviewed the document until the `subscribeEvent` section. I'll open some issues related to this review process since I was not sure to modify the document.
Sorry for the messed git timeline. I do not know why but it seems that the commits from the previous PR were not recognized as already in the master timeline.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/239.html" title="Last updated on Aug 25, 2020, 3:00 PM UTC (0f2770a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/239/75dc2b2...relu91:0f2770a.html" title="Last updated on Aug 25, 2020, 3:00 PM UTC (0f2770a)">Diff</a>
=> My review feedback

index.html
see https://github.com/w3c/wot-scripting-api/issues/230#issuecomment-668142199
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/250.html" title="Last updated on Aug 25, 2020, 3:46 PM UTC (361d880)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/250/db86ec8...danielpeintner:361d880.html" title="Last updated on Aug 25, 2020, 3:46 PM UTC (361d880)">Diff</a>
=> chore: updates for Chapter 6 based on PDF comments from Ege

index.html
Also, autocorrect typos/white space errors.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/254.html" title="Last updated on Aug 26, 2020, 7:27 PM UTC (97b9ef2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/254/243de60...zolkis:97b9ef2.html" title="Last updated on Aug 26, 2020, 7:27 PM UTC (97b9ef2)">Diff</a>
=> Remove Open Issue section, fixing #253.

index.html
Simplify the example and close issue #245. Examples for advanced usage of `InteractionOutput` could be added later. I have already some draft examples [here](https://gist.github.com/relu91/05928793fbed8e95b1db0035c9038bf7#low-level-interactions-draft).
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/255.html" title="Last updated on Aug 27, 2020, 4:32 PM UTC (9510a95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/255/243de60...relu91:9510a95.html" title="Last updated on Aug 27, 2020, 4:32 PM UTC (9510a95)">Diff</a>
=> Update consume thing consume example

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/260.html" title="Last updated on Sep 14, 2020, 10:17 AM UTC (a0aa273)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/260/c8ae596...zolkis:a0aa273.html" title="Last updated on Sep 14, 2020, 10:17 AM UTC (a0aa273)">Diff</a>
=> Fix #243: make ReadHandler description more concise

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/261.html" title="Last updated on Sep 14, 2020, 10:25 AM UTC (48526d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/261/c8ae596...zolkis:48526d8.html" title="Last updated on Sep 14, 2020, 10:25 AM UTC (48526d8)">Diff</a>
=> Fix #251: improve the emitEvent() algorithm

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/266.html" title="Last updated on Sep 23, 2020, 12:18 PM UTC (c165e59)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/266/758beb5...zolkis:c165e59.html" title="Last updated on Sep 23, 2020, 12:18 PM UTC (c165e59)">Diff</a>
=> Fix ReSpec header with new group field

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/269.html" title="Last updated on Oct 5, 2020, 10:57 AM UTC (50a0bc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/269/28824c5...zolkis:50a0bc6.html" title="Last updated on Oct 5, 2020, 10:57 AM UTC (50a0bc6)">Diff</a>
=> Improve error handling for ExposedThing:emitEvent()

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/277.html" title="Last updated on Oct 20, 2020, 12:34 PM UTC (a572662)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/277/2cdd539...zolkis:a572662.html" title="Last updated on Oct 20, 2020, 12:34 PM UTC (a572662)">Diff</a>
=> Fixes #223: update Changes section

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/288.html" title="Last updated on Jan 11, 2021, 1:14 PM UTC (489d25e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/288/80cc5f7...489d25e.html" title="Last updated on Jan 11, 2021, 1:14 PM UTC (489d25e)">Diff</a>
=> apply the diff with the Note1 version

typescript/index.d.ts
Synchronize Typescript types with the latest changes in #305
=> Introduce PropertyReadMap and PropertyWriteMap in TS

.github/workflows/sync.yml
=> chore: ci bump node version

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/371.html" title="Last updated on Jan 24, 2022, 4:59 PM UTC (4639bf2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/371/727cdb1...danielpeintner:4639bf2.html" title="Last updated on Jan 24, 2022, 4:59 PM UTC (4639bf2)">Diff</a>
=> Fixes some minor typos/issues

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/375.html" title="Last updated on Feb 14, 2022, 7:04 PM UTC (560d10c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/375/f234394...zolkis:560d10c.html" title="Last updated on Feb 14, 2022, 7:04 PM UTC (560d10c)">Diff</a>
=> Fix #355: change use cases

.github/workflows/sync.yml
=> Sync-td runs before sync-tm

index.html
Note: These are just minor suggestions, please let me know if you disagree.
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/452.html" title="Last updated on Feb 7, 2023, 1:29 PM UTC (24f496f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/452/2708c45...danielpeintner:24f496f.html" title="Last updated on Feb 7, 2023, 1:29 PM UTC (24f496f)">Diff</a>
=> Some minor typos/alignments 

typescript/package-lock.json, typescript/scripting-api/package.json
fixes https://github.com/w3c/wot-scripting-api/issues/457
=> add wot-thing-description-types as dependency for scripting api

index.html
Should eventually fix #447.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/463.html" title="Last updated on Mar 20, 2023, 5:22 PM UTC (33861b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/463/f950ea5...relu91:33861b7.html" title="Last updated on Mar 20, 2023, 5:22 PM UTC (33861b7)">Diff</a>
=> Fix internal slot in event handlers

README.md
Related to #224 and closes #458
=> Update README.md with versioning information

typescript/package-lock.json, typescript/scripting-api/package.json, typescript/thing-description/package.json, typescript/thing-model/package.json
fixes https://github.com/w3c/wot-scripting-api/issues/484
fixes https://github.com/w3c/wot-scripting-api/issues/485
=> chore: update TS definitions based on TD JSON schema updates

releases/note2/index.html, releases/note2/static.html
following the ordinary procedure like https://github.com/w3c/wot-binding-templates/blob/main/publication/README.md
=> regenerate static.html

releases/note2/index.html
=> use defer instead of async

releases/note2/index.html
see also: https://github.com/w3c/respec/wiki/githubAPI
=> use github instead of githubAPI

typescript/package-lock.json, typescript/scripting-api/package.json, typescript/thing-description/package.json, typescript/thing-model/package.json
due to https://github.com/w3c/wot-thing-description/pull/1844
fixes https://github.com/w3c/wot-scripting-api/issues/499 and https://github.com/w3c/wot-scripting-api/issues/500
=> chore: update TS versions

releases/note2/backup.html, releases/note2/fix-id.pl
to fix the issue with the duplicated IDs generated by ReSpec automatically
=> add a postprocess script

releases/note2/Overview.html, releases/note2/backup.html
failed to update Overview.html :(
so regenerate it
=> pubdate 2023-10-03 again

index.html
fixes https://github.com/w3c/wot-scripting-api/issues/497
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/514.html" title="Last updated on Oct 23, 2023, 1:27 PM UTC (48a3cf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/514/119c2a0...danielpeintner:48a3cf5.html" title="Last updated on Oct 23, 2023, 1:27 PM UTC (48a3cf5)">Diff</a>
=> refactor: Update working draft with changes done for note2 publication 

typescript/package-lock.json, typescript/scripting-api/package.json, typescript/thing-description/package.json, typescript/thing-model/package.json
fixes https://github.com/w3c/wot-scripting-api/issues/520 and https://github.com/w3c/wot-scripting-api/issues/521
=> refactor: update TD/TM schemas / dependencies

typescript/package-lock.json
see https://github.com/w3c/wot-scripting-api/pull/513/files
=> chore: increase root package-lock.json

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/564.html" title="Last updated on Oct 15, 2024, 8:12 AM UTC (af4d6bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/564/aa7dbe8...af4d6bf.html" title="Last updated on Oct 15, 2024, 8:12 AM UTC (af4d6bf)">Diff</a>
=> Minor typo in example code

typescript/README.md
Similar to https://github.com/w3c/wot-scripting-api/pull/575  for subfolders
=> Update README.md with tag for subfolder
