w3c/wot-scripting-api

index.html

WebIDL was updated based on comments in #3.
Added some of the use cases mentioned in #6.

Add use cases. Refactor WebIDL.

---

index.html

addressing #18 
defaulting to writeable.
using default false value according to [WebIDL recommendation](https://www.w3.org/TR/WebIDL-1/#dfn-dictionary-member-default-value), therefore readOnly instead of writeable.

adding readOnly entry for Property initializer

---

index.html

Most of this PR consists of editorial fixes (white spaces, indentation, etc).
Some of the terminology is fixed using definitions from https://github.com/w3c/wot-architecture/wiki/Terminology.
Reworked the WoT interface section with new structure, to be used in other sections as well.

Editorial changes. Rework WoT API section with new structure.

---

index.html

- Rename `WoT.retrieve()` to `consume()` and `createLocalThing()` to `expose()`.
- Remove the Client API and Server API as sections and just mention ConsumedThing is client API and ExposedThing is server API.
- Replace general nouns property action and event to defined/linked terms for WoT Property, Action and Event.

FPWD edits

---

index.html

Replace (broken, incomplete) security section with simple pointer to wot-security repo.  For some reason I can't merge and can't fetch the current state of the repo to resolve conflicts, however, so this PR will have to be merged manually.

update security section editor's note

---

index.html

DiscoveryType does not exist --> now points to https://w3c.github.io/wot-scripting-api/#the-discoverymethod-enumeration

ThingFilter uses non-existing/wrong enum

---

index.html

Don't merge yet, this is work in progress.
For the rendered version of the tip of the PR, use [this link](http://rawgit.com/zolkis/wot-scripting-api/master/index.html).

Update the API according to discussion in #82 and #78

---

primer/README.md

Currently HTML is escaped and images are not displayed at:
https://w3c.github.io/wot-scripting-api/primer/
Bug: https://github.com/w3c/wot-scripting-api/issues/79
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

Fix markdown images links

---

index.html

Following https://github.com/w3c/wot-thing-description/pull/95
Fixes #94 and #89.

Use schema, inputSchema, outputSchema from updated TD spec. Add support for TD links.

---

index.html

The field `semanticTypes` of SemanticAnnotations should be `semanticType`.

Use singular for field names (LD convention)

---

index.html

Always follow the same order for consistency and easier reference/navigation.

Follow consistent Properties-Actions-Events order

---

index.html

Changed examples to new API.
Tested with node-wot, except `setPropertyReadHandler()`.

Fix examples

---

index.html

Please do not merge until everyone has commented. 
If possible, we would like to discuss this PR at the next scripting call on Monday.

Rewriting S&P section without normative statements

---

index.html

Add explanatory text for target groups.
Add input checks to Scripting Runtime security section.
Other than that, for time being keep all the original risk and mitigation sections.

Reorganize the Security section

---

index.html

Change the spec based on the discussions during the last 2 F2F and since them.
This is a major change:
- fetch() was outsourced to external APIs
- Observables removed, based on discussions on TPAC
- TAG design principles applied
- the WOT object changed to contain only consume(), produce(), discover().
- discovery has changed to use events and a design that matches with other W3C specifications for similar functionality (e.g. Generic Sensors API)
- the concept of ThingInstance has been defined and when using it in combination with Thing constructors, a lot of the former data-API could be removed.

Rewrite the spec according to past few months discussions for the new WD

---

index.html

Add a section in ExposedThing about methods inherited from ConsumedThing and clarify default handlers provided by implementations (via bindings) and script provided handlers.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/187.html" title="Last updated on Aug 27, 2019, 11:20 AM UTC (e9edde4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/187/c8b3b8a...zolkis:e9edde4.html" title="Last updated on Aug 27, 2019, 11:20 AM UTC (e9edde4)">Diff</a>

Clarify ExposedThing default handlers vs script provided handlers. Editorial fixes.

---

index.html

Feedback from the draft for wd4 publication at:
https://github.com/w3c/wot-scripting-api/blob/master/releases/wd4/Overview.html
The changes are:
* add Editor IDs using w3cid
* fix a broken link of the-start-method as file by adding # and make it #the-start-method
* fix broken links of the-next-method as file by adding # and make it #the-next-method
* use CR version URL for TD
* use CR version URL for Architecture
* not json-schema-4-validation but json-schema-for-validation (twice)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/197.html" title="Last updated on Oct 28, 2019, 5:12 PM UTC (60bbd87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/197/bc6c766...60bbd87.html" title="Last updated on Oct 28, 2019, 5:12 PM UTC …

feedback from wd4

---

index.html
rationale.md

Captures the decision made in the Scripting call on 24.2.2020: 
- include an ed's note about write and return values
- update the design rationale file.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/205.html" title="Last updated on Feb 24, 2020, 2:36 PM UTC (ed634fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/205/cd2f7ee...zolkis:ed634fc.html" title="Last updated on Feb 24, 2020, 2:36 PM UTC (ed634fc)">Diff</a>

Returning values from writes

---

index.html

[Work in Progress]
Use more modern spec prose, and the Web Platform cross-referencing.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 10, 2020, 9:16 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fwot-scripting-api%2Fed634fc313e9742df28246bf1776a5978aa2d35d%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough information above to …

Editorial changes

---

index.html

Add InteractionOptions to `unobserveProperty()` and `unsubscribeEvent()`. Addresses #201 
Add `InteractionData` definition, usage and examples. Addresses #208
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/209.html" title="Last updated on Jun 1, 2020, 5:36 PM UTC (45b888a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/209/8037a79...zolkis:45b888a.html" title="Last updated on Jun 1, 2020, 5:36 PM UTC (45b888a)">Diff</a>

Add InteractionData

---

index.html

Also, apply Web IDL namespace rules.

Fix #215: make the API entry point a namespace. 

---

index.html

Point 6: "create interaction datasteps" --> "create interaction data steps"
Typo in header: "Poperties" --> "Properties"
Point 6, "Protocol Bindingsand" --> "Protocol Bindings and"
"observeable" --> "observable"
"with a options object" --> "with an options object "
"occured" --> "occurred"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/229.html" title="Last updated on Aug 3, 2020, 1:37 PM UTC (b1d5240)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/229/f7eef4c...b1d5240.html" title="Last updated on Aug 3, 2020, 1:37 PM UTC (b1d5240)">Diff</a>

docs: minor typos/issues

---

index.html

This PR reports @egekorkan review changes in chapters 4 and 5 (no comments were left on chapter 3). See the related https://github.com/w3c/wot-scripting-api/issues/230#issuecomment-668142199 and the [pdf document](https://github.com/w3c/wot-scripting-api/files/5017322/ScriptingAPI-review-egekorkan.pdf)
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/231.html" title="Last updated on Aug 14, 2020, 9:16 AM UTC (8c948cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/231/f7eef4c...relu91:8c948cf.html" title="Last updated on Aug 14, 2020, 9:16 AM UTC (8c948cf)">Diff</a>

Minor changes on chapters 4 and 5

---

index.html

Also, fix ReSpec errors (on streams).
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/234.html" title="Last updated on Aug 19, 2020, 12:03 PM UTC (1ec0a9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/234/16a28ee...zolkis:1ec0a9e.html" title="Last updated on Aug 19, 2020, 12:03 PM UTC (1ec0a9e)">Diff</a>

Address #230: update first chapters

---

index.html

As the title says this PR adds three examples to the Consume Thing object. In particular, the examples show usages of `arrayBuffer` and `ReadableStream`.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/257.html" title="Last updated on Aug 31, 2020, 3:23 PM UTC (d39bbd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/257/05c3eaf...relu91:d39bbd3.html" title="Last updated on Aug 31, 2020, 3:23 PM UTC (d39bbd3)">Diff</a>

Add more Consume Thing examples

---

README.md
rationale.md

Update README and rationale

---

index.html

This requires more discussion, e.g. how do we check that each interaction has a Form from each protocol mentioned in overall set of Forms. In this PR I left that check to the implementation's discretion.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/262.html" title="Last updated on Sep 14, 2020, 2:25 PM UTC (cf5bff0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/262/c8ae596...zolkis:cf5bff0.html" title="Last updated on Sep 14, 2020, 2:25 PM UTC (cf5bff0)">Diff</a>

Fix #258: improve expose() algorithm

---

index.html

WiP:
- moved one clause from consume() to ConsumedThing constructor
- however, binding initialization step is problematic in constructor.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/259.html" title="Last updated on Sep 14, 2020, 2:23 PM UTC (c9ee6a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/259/c8ae596...zolkis:c9ee6a8.html" title="Last updated on Sep 14, 2020, 2:23 PM UTC (c9ee6a8)">Diff</a>

Fix #244: ConsumeThing constructor and consume() should do the same

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/264.html" title="Last updated on Sep 23, 2020, 9:52 AM UTC (01e3475)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/264/7a59934...zolkis:01e3475.html" title="Last updated on Sep 23, 2020, 9:52 AM UTC (01e3475)">Diff</a>

Fix #237 and #256: handle subscription errors

---

typescript/index.d.ts

I finally found a solution to have our typescript definition file work both in module and no-module environments. Practically this means that `tsc` will validate both of those code snippets:
```ts
WoT.produce(td).then((thing:WoT.ExposedThing)=>{/*...*/});
```
```ts
import {produce,ExposedThing} from "WoT";
produce(td).then((thing:ExposedThing)=>{/*...*/});
```
As a example the first one might be written inside WoT scripts (which may not support a module system) and the latter for runtimes who want to use node-wot as a library.
Since I had to format the file it is quite difficult to undestand the change. Essentially I changed the declaration of the namespace from `export as namespace WoT;` to:
```ts
declare namespace WoT {
/* declarations */
}
```
Finally I exposed every field in the …

Proposal for typescript definition file

---

typescript/index.d.ts

As pointed by @danielpeintner in this comment: https://github.com/w3c/wot-scripting-api/pull/265#issuecomment-698334103, our fight with typescript definition file has not ended. This PR should fix the issue reported in the comment. Plus we'll probably write a warning saying that this file definition is only valid for ES6 and above.

Fix typescript definition module name

---

index.html

+ removes references for wot-security best practices and testing which are all part of wot-security document
fixes https://github.com/w3c/wot-scripting-api/issues/252
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/271.html" title="Last updated on Oct 8, 2020, 1:19 PM UTC (29648af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/271/7a5d14a...danielpeintner:29648af.html" title="Last updated on Oct 8, 2020, 1:19 PM UTC (29648af)">Diff</a>

feat: remove section about "Stale TD Security Risk"

---

index.html

As the title says, this PR attempts to clarify the usage of WoT Interaction instead of Interaction Affordances. I added both an Editor's and a term definition inside section 11. Please let me know if it can be improved.
Fixes #241
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/272.html" title="Last updated on Oct 13, 2020, 4:12 PM UTC (b9a513e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/272/3592d77...relu91:b9a513e.html" title="Last updated on Oct 13, 2020, 4:12 PM UTC (b9a513e)">Diff</a>

Add editor's note about WoT interactions vs Interaction Affordances

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/276.html" title="Last updated on Oct 19, 2020, 12:17 PM UTC (4449710)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/276/94d9028...danielpeintner:4449710.html" title="Last updated on Oct 19, 2020, 12:17 PM UTC (4449710)">Diff</a>

update WOT references to latest publication URL/date

---

index.html

Sorry, I forgot to create a PR about this. I also noticed that other terms from Thing Description are not linked. Opening an issue about it in a second.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/279.html" title="Last updated on Oct 22, 2020, 4:52 PM UTC (8bdf0c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/279/e3ebd7b...relu91:8bdf0c7.html" title="Last updated on Oct 22, 2020, 4:52 PM UTC (8bdf0c7)">Diff</a>

Fix WoT network interface definition

---

index.html

add explicit emitPropertyChange() and remove ConsumedThing inheritance from ExposedThing
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/283.html" title="Last updated on Nov 16, 2020, 1:50 PM UTC (2306bca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/283/8bdf0c7...zolkis:2306bca.html" title="Last updated on Nov 16, 2020, 1:50 PM UTC (2306bca)">Diff</a>

Fix #280 and 281: add emitPropertyChange(), remove ConsumedThing inheritance

---

index.html
typescript/index.d.ts
typescript/package.json

see https://github.com/w3c/wot-scripting-api/issues/290
aligns TS definitions also (no NPM publish yet)
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/291.html" title="Last updated on Jan 25, 2021, 1:26 PM UTC (c7fe51d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/291/6c88d6b...danielpeintner:c7fe51d.html" title="Last updated on Jan 25, 2021, 1:26 PM UTC (c7fe51d)">Diff</a>

fix: PropertyReadHandler returning promise with InteractionInput

---

index.html
typescript/index.d.ts
typescript/package.json

see https://github.com/w3c/wot-scripting-api/issues/294
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/295.html" title="Last updated on Jan 26, 2021, 7:06 AM UTC (aad7506)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/295/2e0dea3...danielpeintner:aad7506.html" title="Last updated on Jan 26, 2021, 7:06 AM UTC (aad7506)">Diff</a>

feat: use DataSchemaValue for value() function in InteractionOutput

---

index.html

This PR introduces the new concept of a PartialTD defined in the architecture PR: https://github.com/w3c/wot-architecture/pull/577.
The changes are heavier than I thought therefore I'd like to receive some feedback about the direction that I am taking. 
As you can see I changed the argument type of the `produce` method to `PartialTD`. This is because a Thing Description is also an instance of a `PartialTD`; in fact, the validation algorithm would accept any valid TD. 
Another open point is how we transform a `PartialTD` to a valid `Thing Description`. I tried to sketch an algorithm in this PR; please have look.
Notice finally, how these changes affect the construction of an `ExposedThing`. Now the constructor has first to transform the `PartialTD` and then extend the obtained TD with the …

Add definitions for partialTD

---

index.html

It also did some white space corrections automatically.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/305.html" title="Last updated on Mar 1, 2021, 9:20 AM UTC (e3529c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/305/5d70e76...zolkis:e3529c9.html" title="Last updated on Mar 1, 2021, 9:20 AM UTC (e3529c9)">Diff</a>

Factor out maplike interfaces property reads and writes

---

index.html

Fixes #311 
Now that discovery methods are simplified, `url` could become a first-class mandatory parameter to `discover()`.
However, that would limit future extension to multicast discovery, if ever comes.
So the current design is still the most generic and robust.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/316.html" title="Last updated on Apr 26, 2021, 7:52 AM UTC (382ba63)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/316/e3529c9...zolkis:382ba63.html" title="Last updated on Apr 26, 2021, 7:52 AM UTC (382ba63)">Diff</a>

Simplify discovery methods. Update examples.

---

typescript/index.d.ts

This change should fix problems when trying to use the new types in node-wot or scripts. Furthermore, it aligns the produce method with the current spec. Now it accepts a PartialThingDescription interface defined as a ThingDescription but with everything optional.

Allign types with the current specification

---

.github/workflows/sync.yml
typescript/package.json
typescript/thing-description.d.ts

Just noticed that the GitHub action did not update the ts file generated but only the schema. There is still an issue with the name of the schema that needs to manually (using bash) replaced. I'll open a PR on the TD repo to use a version field instead of putting it in the title.

Fix sync action 

---

index.html

Might fix #334. I looked through the document and it seems that we just left consumer side algorithms without NotFoundError. In ExposedThings we already provide a dedicated step to throw NotFoundErrors.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/339.html" title="Last updated on Sep 20, 2021, 9:14 AM UTC (7411767)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/339/dfaed06...relu91:7411767.html" title="Last updated on Sep 20, 2021, 9:14 AM UTC (7411767)">Diff</a>

Add NotFoundError for consumer algorithms

---

index.html

resolves part#1 of https://github.com/w3c/wot-scripting-api/issues/342
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/353.html" title="Last updated on Nov 29, 2021, 3:39 PM UTC (132fd6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/353/ad7a37a...danielpeintner:132fd6d.html" title="Last updated on Nov 29, 2021, 3:39 PM UTC (132fd6d)">Diff</a>

refactor: move section "Terminology and conventions" right after "Conformance"

---

index.html

This PR adds an additional step to `observeProperty` and `subscribeEvent` algorithms of the `ConsumeThing`. It forces the runtime implementation to check whether the affordance has already an active Subscription, and if it is the case the runtime must throw a `NotAllowedError`. This should make clear to implementers that it is not possible to subscribe multime times to the same affordance, but I also added an editor note to make it cristal clear. 
The PR is currently in draft mode cause I wanted to use [Set](https://tc39.es/ecma262/#sec-set-objects) as type of the list of active Subscriptions/Observations but ECMA specification is not included among our `xref` and it conflicts with `web-platform`. 
*Note*: It covers the points raised in #346.
***
<a …

Allow only one subscription per affordance

---

index.html

fixes https://github.com/w3c/wot-scripting-api/issues/357
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/367.html" title="Last updated on Jan 20, 2022, 1:20 PM UTC (ef93304)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/367/c244340...danielpeintner:ef93304.html" title="Last updated on Jan 20, 2022, 1:20 PM UTC (ef93304)">Diff</a>

Correctly reference/use definitions

---

index.html

fix: make clear that document is not on REC track
fixes https://github.com/w3c/wot-scripting-api/issues/365
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/368.html" title="Last updated on Jan 31, 2022, 2:00 PM UTC (9acc6d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/368/c244340...danielpeintner:9acc6d7.html" title="Last updated on Jan 31, 2022, 2:00 PM UTC (9acc6d7)">Diff</a>

resolve ReSpec warnings

---

typescript/thing-description/package.json
typescript/thing-description/thing-description.d.ts

https://github.com/w3c/wot-thing-description/pull/1319 introduced a schema definition for `Form`. In principle, this new definition was added to let typescript users have a type for a generic form. Sadly, [json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript) does not automatically do it but you have to enable it. This PR enables the generation of unreachable definitions. As you can see on the diff enabling such option causes also the generation of a long list of unwanted comments. I tried to get rid of them without any success. I'm waiting for [an answer](https://github.com/bcherny/json-schema-to-typescript/issues/428) from the main contributors to remove them, meanwhile, I think we can live with them.

Generate types for unreachable definitions

---

.github/workflows/sync.yml

I would like to keep the two jobs parallel, therefore I've added a pull action before pushing to the upstream. In theory one of the two jobs might still push changes while the other has already pulled... but I want to give this a try. Fixes #382

Pull before pushing in the CI

---

typescript/package-lock.json
typescript/scripting-api/index.d.ts
typescript/scripting-api/package.json

Question: Did we simply miss it or was there a reason for leaving it out?

fix: add missing emitPropertyChange() method

---

index.html

fixes https://github.com/w3c/wot-scripting-api/issues/407
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/415.html" title="Last updated on Jul 11, 2022, 3:32 PM UTC (f9de18f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/415/cf3d575...danielpeintner:f9de18f.html" title="Last updated on Jul 11, 2022, 3:32 PM UTC (f9de18f)">Diff</a>

refactor: remove observeHandler from  emitPropertyChange() steps

---

index.html

fixes https://github.com/w3c/wot-scripting-api/issues/403
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/414.html" title="Last updated on Jul 18, 2022, 12:23 PM UTC (2f2d1ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/414/cf3d575...danielpeintner:2f2d1ca.html" title="Last updated on Jul 18, 2022, 12:23 PM UTC (2f2d1ca)">Diff</a>

refactor: move allowed types out of the parenthesis to make it more official

---

index.html

PR https://github.com/w3c/wot-scripting-api/pull/423 introduced the emphasis for _empty._ I suggest to remove it all together. 
1. `emph` is for LaTeX (my fault), in HTML it should be `<em>`
2. I quickly skimmed the current document and we use empty without emphasizing
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/432.html" title="Last updated on Sep 26, 2022, 12:16 PM UTC (7b8f4ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/432/c7c2cf2...7b8f4ee.html" title="Last updated on Sep 26, 2022, 12:16 PM UTC (7b8f4ee)">Diff</a>

refactor: fix/remove emphasised empty

---

index.html

This is an attempt to create Web IDL definitions based on the example in https://github.com/w3c/wot-scripting-api/issues/364#issuecomment-1137703749. This is still a work in progress and far from mergeable, but we might already be able to use for discussing the details of the new API.
The most important changes are the addition of the [async iterable](https://webidl.spec.whatwg.org/#idl-async-iterable) keywords and the removal of the `next()` method (which is now available on the inherited `Symbol.asyncIterator` field). Assuming that the discovery process should start right away, I also removed the `start()` method. However, if it is good practice to have such a method in a web API, then it could of course still be included. 
Furthermore, as both the `direct` and the `directory` methods …

feat!: add new Discovery Web IDL definitions

---

index.html

Introduce separate methods for requesting to fetch a TD, for directory discovery and for generic discovery.
Rename ThingDiscovery to ThingDiscoveryProcess.
Remove |url| from ThingFilter and make it internal slot to ThingDiscoveryProcess. Remove |filter| from ThingDiscoveryProcess and make it internal slot to ThingDiscoveryProcess. Remove |active| from ThingDiscoveryProcess.
Define a generic discovery algorithm with meta-argument for generic or directory discovery.
Add the URL standard to the document header / xref.
Address #364
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/wot-scripting-api/pull/441.html" title="Last updated on Dec 19, 2022, 12:32 PM UTC (27f9442)">Preview</a> | <a …

Align the discovery API with the Discovery spec

---

index.html
typescript/package-lock.json
typescript/scripting-api/index.d.ts
typescript/scripting-api/package.json

resolves https://github.com/w3c/wot-scripting-api/issues/402
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/442.html" title="Last updated on Dec 14, 2022, 12:37 PM UTC (c323d8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/442/6fcfdb6...danielpeintner:c323d8a.html" title="Last updated on Dec 14, 2022, 12:37 PM UTC (c323d8a)">Diff</a>

fix: emitEvent() method allows data to be optional

---

index.html

I noticed that we are not correctly referencing the internal slots we defined. Moreover, in `ExposedThing` we are using internal slots in the "old way". I'd like to fix this issue too.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-scripting-api/pull/424.html" title="Last updated on Dec 19, 2022, 6:28 PM UTC (b76dcee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/424/6fcfdb6...relu91:b76dcee.html" title="Last updated on Dec 19, 2022, 6:28 PM UTC (b76dcee)">Diff</a>

Fix internal slots

---

index.html

Note: I also checked whether the anchors still exist, like 
https://www.w3.org/TR/2023/CR-wot-architecture11-20230119/#dfn-interaction-affordance
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/451.html" title="Last updated on Feb 7, 2023, 1:19 PM UTC (458ea9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/451/2708c45...danielpeintner:458ea9f.html" title="Last updated on Feb 7, 2023, 1:19 PM UTC (458ea9f)">Diff</a>

update URLs to last published document

---

index.html

* https://fetch.spec.whatwg.org
* https://streams.spec.whatwg.org
* https://html.spec.whatwg.org
fixes https://github.com/w3c/wot-scripting-api/issues/459
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/464.html" title="Last updated on Mar 6, 2023, 3:41 PM UTC (3dc84d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/464/14ff4ac...danielpeintner:3dc84d3.html" title="Last updated on Mar 6, 2023, 3:41 PM UTC (3dc84d3)">Diff</a>

Use biblio references for more URLs

---

releases/note2/index.html

[Preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/wot-scripting-api/adc0aa95db7feb27c27fa253974b3eb44e8025f5/releases/note2/index.html)
NOTE: All (some?) of the fixes should go into the main note as well in a follow-up PR
fixes https://github.com/w3c/wot-scripting-api/issues/475

2023 note2 updates2

---

index.html

same changes as in https://github.com/w3c/wot-scripting-api/pull/477 but for the master branch
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-scripting-api/pull/478.html" title="Last updated on May 19, 2023, 11:26 AM UTC (02a5fbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/478/e5a917c...danielpeintner:02a5fbc.html" title="Last updated on May 19, 2023, 11:26 AM UTC (02a5fbc)">Diff</a>

Fix HTML issues

---

index.html

Align with changes in other repos, e.g, https://github.com/w3c/wot-thing-description/pull/1899
@zolkis
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 18, 2023, 1:37 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwot-scripting-api%2F119c2a0dae2f53cd53b7baf81180b75b3bd025e3%2Findex.html%3FisPreview%3Dtrue)
```
😭  Sorry, there was an error generating the HTML. Please report this …
```

fix: "Intel" usage to "Intel Corp."

---

typescript/scripting-api/index.d.ts
typescript/scripting-api/package.json

In the context of https://github.com/eclipse-thingweb/node-wot/pull/864, I noticed that the TypeScript definitions are not taking into account the latest changes to the Scripting APIs discovery API (see https://github.com/w3c/wot-scripting-api/pull/405 and https://github.com/w3c/wot-scripting-api/pull/441). This PR should adjust the types accordingly – let me know if I missed anything :)

feat!(typescript): align TypeScript definitions with Discovery API

---

index.html

Would resolve #516 and close #515 (as an alternative PR).
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/517.html" title="Last updated on Oct 29, 2023, 10:06 PM UTC (03b740d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/517/119c2a0...JKRhb:03b740d.html" title="Last updated on Oct 29, 2023, 10:06 PM UTC (03b740d)">Diff</a>

feat!: remove constructor from ConsumedThing interface

---

index.html

In the current Editor's draft, there are a couple of leftovers from previous versions where the `requestThingDescription` had not been introduced yet. This PR updates the text, incorporates the latest changes, and also removes an outdated appendix that explains why there is no fetch method anymore (which has now de facto been reintroduced). Maybe some text regarding the validation of TDs could be added/moved elsewhere, though.
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/524.html" title="Last updated on Dec 4, 2023, 3:19 PM UTC (329213a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/524/6482a8c...JKRhb:329213a.html" title="Last updated on Dec 4, 2023, 3:19 PM UTC (329213a)">Diff</a>

Update text and examples regarding the fetching of TDs

---

index.html

fixes https://github.com/w3c/wot-scripting-api/issues/542
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 1, 2024, 3:33 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fdanielpeintner%2Fwot-scripting-api%2F8d34032e01cfa16f813ff02d99aee6147de290ed%2Findex.html%3FisPreview%3Dtrue)
```
error code: 502
```
_If you don't have enough information above to solve the error by yourself (or to …

fix: respec warnings about anchor/link

---

index.html

At the moment, the `value` function of the `InteractionOutput` interface requires the `type` field of its `schema` to be set. In a discussion over at https://github.com/eclipse-thingweb/node-wot/issues/1221, we identified this as a problem for several different scenarios, including the `exloreDirectory` method, as the `things` property of the Thing Description Directory API specification does not contain a `type` field itself, as there are two different types that can be obtained from the property (namely, an array or an object of TDs).
Therefore, this PR proposes changing the algorithm to not throw anymore when the field should be `null` or `undefined`, making it usable in more scenarios.
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/534.html" title="Last …

fix(InteractionOutput): don't require schema.type in value function

---

README.md

see https://github.com/w3c/wot/blob/main/README.template.md
assigned in https://github.com/w3c/wot-marketing/issues/461#issuecomment-2090303677

refactor: align with latest marketing template

---

index.html

The project has a new GitHub organization now and https webpage instead of http
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/pull/549.html" title="Last updated on Apr 29, 2024, 1:28 PM UTC (6334fc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/549/ab7cd69...6334fc0.html" title="Last updated on Apr 29, 2024, 1:28 PM UTC (6334fc0)">Diff</a>

Eclipse Thingweb links fixes

---

index.html

I noticed that there are currently a couple of manually defined references, which we can replace with ones provided by Specref for more consistency and – in the case of specifications that are less “stable” – automated updates whenever a new document is being published.
Note that I used the latest REC versions for TD, Discovery, and Architecture – not sure if it would make sense to also point to the latest version here instead when possible.
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/552.html" title="Last updated on May 15, 2024, 8:08 AM UTC (877153c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/552/23dc59e...JKRhb:877153c.html" title="Last updated on May 15, 2024, 8:08 AM UTC (877153c)">Diff</a>

chore: use references from specref instead local bibliography

---

index.html

As discussed in https://github.com/w3c/wot-thing-description/pull/2029, this simply also enables dark mode support for this repository.
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/556.html" title="Last updated on Jul 8, 2024, 8:30 AM UTC (bf90f2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-scripting-api/556/352fe0c...JKRhb:bf90f2e.html" title="Last updated on Jul 8, 2024, 8:30 AM UTC (bf90f2e)">Diff</a>

chore: enable dark mode support

---

index.html

This PR takes over the commit discussed under https://github.com/w3c/wot-scripting-api/pull/551#discussion_r1632756745. However, I already adjusted it insofar that I removed the adjustments of the constructor, not adding an optional `url` parameter.
However, since the field is set "externally" in the current `exploreDirectory` algorithm, I think it would still make sense to adjust the data structure here to make it "less mutable" if not immutable if possible. If I see it correctly, one way to achieve this in WebIDL could be defining a [second constructor](https://webidl.spec.whatwg.org/#idl-constructors) with a mandatory URL parameter. Maybe this something we could discuss in today's call.
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-scripting-api/pull/557.html" title="Last …

fix(ThingDiscoveryProcess): clarify usage of url field

---

index.html

After the discussions we had on Monday, I dealt a little more with the usage of the `discover` method and I realized that we are actually in quite a good shape there already if we simply keep the method generic and let the underlying implementation handle the details of how the discovery is supposed to be performed.
However, in order to make it a bit clearer, how the `discover` method relates to the concepts of introduction and exploration from the discovery specification, this PR adds an explanatory paragraph after the main discover algorithm. With that in place, we could simply let implementors add ways to configure their respective platform (e.g., the `Servient` class in the case of `node-wot`) to use the right mechanism for the job.
Besides that, this PR also makes some minor changes …

Add clarifications for `discover` method

---

typescript/README.md

`--tag latest` is necessary to show up as _latest_ on NPM

Update README with tag
